
package com.changhong.sei.auth.webservice.finEipTodoList;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "DONLIM_EIP_QUERYTODOLISTSYNC_648", targetNamespace = "http://www.example.org/DONLIM_EIP_QUERYTODOLISTSYNC_648/", wsdlLocation = "http://192.168.119.83:7802/WS/DONLIM/EIP/DONLIM_EIP_QUERYTODOLISTSYNC?wsdl")
public class DONLIMEIPQUERYTODOLISTSYNC648_Service
    extends Service
{

    private final static URL DONLIMEIPQUERYTODOLISTSYNC648_WSDL_LOCATION;
    private final static WebServiceException DONLIMEIPQUERYTODOLISTSYNC648_EXCEPTION;
    private final static QName DONLIMEIPQUERYTODOLISTSYNC648_QNAME = new QName("http://www.example.org/DONLIM_EIP_QUERYTODOLISTSYNC_648/", "DONLIM_EIP_QUERYTODOLISTSYNC_648");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.119.83:7802/WS/DONLIM/EIP/DONLIM_EIP_QUERYTODOLISTSYNC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DONLIMEIPQUERYTODOLISTSYNC648_WSDL_LOCATION = url;
        DONLIMEIPQUERYTODOLISTSYNC648_EXCEPTION = e;
    }

    public DONLIMEIPQUERYTODOLISTSYNC648_Service() {
        super(__getWsdlLocation(), DONLIMEIPQUERYTODOLISTSYNC648_QNAME);
    }

    public DONLIMEIPQUERYTODOLISTSYNC648_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DONLIMEIPQUERYTODOLISTSYNC648_QNAME, features);
    }

    public DONLIMEIPQUERYTODOLISTSYNC648_Service(URL wsdlLocation) {
        super(wsdlLocation, DONLIMEIPQUERYTODOLISTSYNC648_QNAME);
    }

    public DONLIMEIPQUERYTODOLISTSYNC648_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DONLIMEIPQUERYTODOLISTSYNC648_QNAME, features);
    }

    public DONLIMEIPQUERYTODOLISTSYNC648_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DONLIMEIPQUERYTODOLISTSYNC648_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DONLIMEIPQUERYTODOLISTSYNC648
     */
    @WebEndpoint(name = "DONLIM_EIP_QUERYTODOLISTSYNC_648SOAP")
    public DONLIMEIPQUERYTODOLISTSYNC648 getDONLIMEIPQUERYTODOLISTSYNC648SOAP() {
        return super.getPort(new QName("http://www.example.org/DONLIM_EIP_QUERYTODOLISTSYNC_648/", "DONLIM_EIP_QUERYTODOLISTSYNC_648SOAP"), DONLIMEIPQUERYTODOLISTSYNC648.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DONLIMEIPQUERYTODOLISTSYNC648
     */
    @WebEndpoint(name = "DONLIM_EIP_QUERYTODOLISTSYNC_648SOAP")
    public DONLIMEIPQUERYTODOLISTSYNC648 getDONLIMEIPQUERYTODOLISTSYNC648SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/DONLIM_EIP_QUERYTODOLISTSYNC_648/", "DONLIM_EIP_QUERYTODOLISTSYNC_648SOAP"), DONLIMEIPQUERYTODOLISTSYNC648.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DONLIMEIPQUERYTODOLISTSYNC648_EXCEPTION!= null) {
            throw DONLIMEIPQUERYTODOLISTSYNC648_EXCEPTION;
        }
        return DONLIMEIPQUERYTODOLISTSYNC648_WSDL_LOCATION;
    }

}
