
package com.changhong.sei.auth.webservice.eipMall;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
//     测试地址：   http://192.168.119.87:7804/WS/DONLIM/ES/AGENCYNOTICEINFOSYNC?wsdl
@WebServiceClient(name = "DONLIM_ES_AGENCYNOTICEINFOSYNC_086", targetNamespace = "http://www.example.org/DONLIM_ES_AGENCYNOTICEINFOSYNC_086/", wsdlLocation = "http://192.168.117.235:7080/WS/DONLIM/ES/AGENCYNOTICEINFOSYNC?wsdl")
public class DONLIMESAGENCYNOTICEINFOSYNC086_Service
    extends Service
{

    private final static URL DONLIMESAGENCYNOTICEINFOSYNC086_WSDL_LOCATION;
    private final static WebServiceException DONLIMESAGENCYNOTICEINFOSYNC086_EXCEPTION;
    private final static QName DONLIMESAGENCYNOTICEINFOSYNC086_QNAME = new QName("http://www.example.org/DONLIM_ES_AGENCYNOTICEINFOSYNC_086/", "DONLIM_ES_AGENCYNOTICEINFOSYNC_086");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.117.235:7080/WS/DONLIM/ES/AGENCYNOTICEINFOSYNC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DONLIMESAGENCYNOTICEINFOSYNC086_WSDL_LOCATION = url;
        DONLIMESAGENCYNOTICEINFOSYNC086_EXCEPTION = e;
    }

    public DONLIMESAGENCYNOTICEINFOSYNC086_Service() {
        super(__getWsdlLocation(), DONLIMESAGENCYNOTICEINFOSYNC086_QNAME);
    }

    public DONLIMESAGENCYNOTICEINFOSYNC086_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DONLIMESAGENCYNOTICEINFOSYNC086_QNAME, features);
    }

    public DONLIMESAGENCYNOTICEINFOSYNC086_Service(URL wsdlLocation) {
        super(wsdlLocation, DONLIMESAGENCYNOTICEINFOSYNC086_QNAME);
    }

    public DONLIMESAGENCYNOTICEINFOSYNC086_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DONLIMESAGENCYNOTICEINFOSYNC086_QNAME, features);
    }

    public DONLIMESAGENCYNOTICEINFOSYNC086_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DONLIMESAGENCYNOTICEINFOSYNC086_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DONLIMESAGENCYNOTICEINFOSYNC086
     */
    @WebEndpoint(name = "DONLIM_ES_AGENCYNOTICEINFOSYNC_086SOAP")
    public DONLIMESAGENCYNOTICEINFOSYNC086 getDONLIMESAGENCYNOTICEINFOSYNC086SOAP() {
        return super.getPort(new QName("http://www.example.org/DONLIM_ES_AGENCYNOTICEINFOSYNC_086/", "DONLIM_ES_AGENCYNOTICEINFOSYNC_086SOAP"), DONLIMESAGENCYNOTICEINFOSYNC086.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DONLIMESAGENCYNOTICEINFOSYNC086
     */
    @WebEndpoint(name = "DONLIM_ES_AGENCYNOTICEINFOSYNC_086SOAP")
    public DONLIMESAGENCYNOTICEINFOSYNC086 getDONLIMESAGENCYNOTICEINFOSYNC086SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/DONLIM_ES_AGENCYNOTICEINFOSYNC_086/", "DONLIM_ES_AGENCYNOTICEINFOSYNC_086SOAP"), DONLIMESAGENCYNOTICEINFOSYNC086.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DONLIMESAGENCYNOTICEINFOSYNC086_EXCEPTION!= null) {
            throw DONLIMESAGENCYNOTICEINFOSYNC086_EXCEPTION;
        }
        return DONLIMESAGENCYNOTICEINFOSYNC086_WSDL_LOCATION;
    }

}
