
package com.changhong.sei.auth.webservice.eipMailTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "DONLIM_ES_AGENCYNOTICEINFOSYNC_086", targetNamespace = "http://www.example.org/DONLIM_ES_AGENCYNOTICEINFOSYNC_086/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DONLIMESAGENCYNOTICEINFOSYNC086 {


    /**
     *
     * @param appHdr
     * @param appBody
     * @param svcHdr0
     * @param svcHdr
     * @param appHdr0
     * @param appBody0
     */
    @WebMethod(operationName = "DONLIM_ES_AGENCYNOTICEINFOSYNC_086", action = "http://www.example.org/DONLIM_ES_AGENCYNOTICEINFOSYNC_086/DONLIM_ES_AGENCYNOTICEINFOSYNC_086")
    @RequestWrapper(localName = "DONLIM_ES_AGENCYNOTICEINFOSYNC_086", targetNamespace = "http://www.example.org/DONLIM_ES_AGENCYNOTICEINFOSYNC_086/", className = "io.renren.modules.ass.webservice.eipMailTest.DONLIMESAGENCYNOTICEINFOSYNC086_Type")
    @ResponseWrapper(localName = "DONLIM_ES_AGENCYNOTICEINFOSYNC_086Response", targetNamespace = "http://www.example.org/DONLIM_ES_AGENCYNOTICEINFOSYNC_086/", className = "io.renren.modules.ass.webservice.eipMailTest.DONLIMESAGENCYNOTICEINFOSYNC086Response")
    public void donlimESAGENCYNOTICEINFOSYNC086(
        @WebParam(name = "SvcHdr", targetNamespace = "")
        SvcHdrType svcHdr,
        @WebParam(name = "AppHdr", targetNamespace = "")
        AppHdrType appHdr,
        @WebParam(name = "AppBody", targetNamespace = "")
        AppBodyType appBody,
        @WebParam(name = "SvcHdr", targetNamespace = "", mode = WebParam.Mode.OUT)
                Holder<SvcHdrTypes> svcHdr0,
        @WebParam(name = "AppHdr", targetNamespace = "", mode = WebParam.Mode.OUT)
                Holder<AppHdrTypes> appHdr0,
        @WebParam(name = "AppBody", targetNamespace = "", mode = WebParam.Mode.OUT)
                Holder<AppBodyTypes> appBody0);

}
